<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <OutputType>Exe</OutputType>
    <RootNamespace>MinCh</RootNamespace>
    <PublishAot>true</PublishAot>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <Description>Minimalist git change tracking</Description>
  </PropertyGroup>
  <PropertyGroup Condition="'$(PackAsTool)' == 'true'">
    <ToolCommandName>minch</ToolCommandName>
    <PackageId>minch</PackageId>
    <Authors>jamesshenry</Authors>
    <PublishTrimmed>true</PublishTrimmed>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <StripSymbols>true</StripSymbols>
    <DefineConstants>$(DefineConstants);PUBLISH_AS_TOOL</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="DotNetPathUtils" Version="0.3.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="MinVer" Version="7.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
    <PackageReference Include="Xdg.Directories" Version="0.1.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MinCh.Library\MinCh.Library.csproj" />
  </ItemGroup>
</Project>
