<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MinCh.Library</RootNamespace>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="MinVer" Version="7.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NetEscapades.EnumGenerators" Version="1.0.0-beta20" />
    <PackageReference Include="Vogen" Version="8.0.4" />
  </ItemGroup>
</Project>
